export enum EPokemonType {
  NORMAL = 'normal',
  BUG = 'bug',
  POISON = 'poison',
  ELETRIC = 'electric',
  FIRE = 'fire',
  WATER = 'water',
  FIGHTING = 'fighting',
  GROUND = 'ground',
  GRASS = 'grass',
  PSYCHIC = 'psychic',
  ROCK = 'rock',
  STEEL = 'steel',
  ICE = 'ice',
  GHOST = 'ghost',
  FAIRY = 'fairy',
  DRAGON = 'dragon',
  FLYING = 'flying',
  UNKNOW = 'unknown',
  SHADOW = 'shadow',
  DARK = 'dark',
}
